import { defineConfig } from "vite"
import fs from "fs"
import path from "path"

/**
 * Vite plugin to enable writing level data to files during development.
 * This allows the Level Designer to persist changes to disk.
 */
function levelFileWriterPlugin() {
  return {
    name: "level-file-writer",
    configureServer(server) {
      // Endpoint for writing to public/levels JSON files
      server.middlewares.use("/__write_levels__", async (req, res) => {
        if (req.method !== "POST") {
          res.statusCode = 405
          res.end("Method not allowed")
          return
        }

        let body = ""
        req.on("data", chunk => {
          body += chunk.toString()
        })

        req.on("end", async () => {
          try {
            const { path: filePath, content } = JSON.parse(body)
            
            // Security: only allow writing to public/levels directory
            if (!filePath.startsWith("public/levels/")) {
              res.statusCode = 403
              res.end("Forbidden: Can only write to public/levels/")
              return
            }

            // Ensure directory exists
            const fullPath = path.resolve(process.cwd(), filePath)
            const dir = path.dirname(fullPath)
            if (!fs.existsSync(dir)) {
              fs.mkdirSync(dir, { recursive: true })
            }

            // Write the file
            fs.writeFileSync(fullPath, content, "utf-8")
            
            console.log(`[level-file-writer] Saved: ${filePath}`)
            
            res.statusCode = 200
            res.setHeader("Content-Type", "application/json")
            res.end(JSON.stringify({ success: true, path: filePath }))
          } catch (e) {
            console.error("[level-file-writer] Error:", e)
            res.statusCode = 500
            res.end(JSON.stringify({ error: e.message }))
          }
        })
      })
      
      // Endpoint for PUBLISHING levels - writes to src/levels/*.js source files
      server.middlewares.use("/__publish_level__", async (req, res) => {
        if (req.method !== "POST") {
          res.statusCode = 405
          res.end("Method not allowed")
          return
        }

        let body = ""
        req.on("data", chunk => {
          body += chunk.toString()
        })

        req.on("end", async () => {
          try {
            const { levelId, levelData } = JSON.parse(body)
            
            // Sanitize levelId for use as filename (remove special chars)
            const safeFileName = levelId.replace(/[^a-zA-Z0-9_-]/g, "_")
            const filePath = `src/levels/${safeFileName}.js`
            const fullPath = path.resolve(process.cwd(), filePath)
            
            // Ensure src/levels directory exists
            const dir = path.dirname(fullPath)
            if (!fs.existsSync(dir)) {
              fs.mkdirSync(dir, { recursive: true })
            }
            
            // Generate the JS file content
            const exportName = safeFileName.replace(/-/g, "_") + "Level"
            const jsContent = `/**
 * ${levelId} Level Data
 * This file is auto-generated by the Level Designer.
 * Direct edits will be overwritten when publishing from the editor.
 * 
 * Last published: ${new Date().toISOString()}
 */

export const ${exportName} = ${JSON.stringify(levelData, null, 2)}
`
            
            // Write the level file
            fs.writeFileSync(fullPath, jsContent, "utf-8")
            console.log(`[level-publisher] Published level: ${levelId} -> ${filePath}`)
            
            // Update the index.js to include this level
            await updateLevelIndex(levelId, safeFileName, exportName)
            
            res.statusCode = 200
            res.setHeader("Content-Type", "application/json")
            res.end(JSON.stringify({ 
              success: true, 
              levelId,
              filePath,
              message: `Level "${levelId}" published successfully!`
            }))
          } catch (e) {
            console.error("[level-publisher] Error:", e)
            res.statusCode = 500
            res.end(JSON.stringify({ error: e.message }))
          }
        })
      })
    }
  }
}

/**
 * Update src/levels/index.js to include new levels
 */
async function updateLevelIndex(levelId, fileName, exportName) {
  const indexPath = path.resolve(process.cwd(), "src/levels/index.js")
  
  let indexContent = ""
  if (fs.existsSync(indexPath)) {
    indexContent = fs.readFileSync(indexPath, "utf-8")
  }
  
  // Check if this level is already imported
  const importLine = `import { ${exportName} } from './${fileName}.js'`
  const dataLine = `  "${levelId}": ${exportName},`
  
  if (!indexContent.includes(importLine)) {
    // Add import at the top (after the comment block)
    const importSection = indexContent.match(/^(\/\*[\s\S]*?\*\/\n*)/)?.[1] || ""
    const afterImports = indexContent.slice(importSection.length)
    
    // Find existing imports
    const existingImports = afterImports.match(/^(import[\s\S]*?\n)*/)?.[0] || ""
    const rest = afterImports.slice(existingImports.length)
    
    indexContent = importSection + existingImports + importLine + "\n" + rest
  }
  
  // Check if level is in LEVEL_DATA
  if (!indexContent.includes(dataLine)) {
    // Add to LEVEL_DATA object
    indexContent = indexContent.replace(
      /export const LEVEL_DATA = \{/,
      `export const LEVEL_DATA = {\n${dataLine}`
    )
  }
  
  fs.writeFileSync(indexPath, indexContent, "utf-8")
  console.log(`[level-publisher] Updated index.js with ${levelId}`)
}

// https://vite.dev/config/
export default defineConfig({
  base: "/game/",
  build: {
    outDir: path.resolve(path.dirname(new URL(import.meta.url).pathname), "dist/public"),
    emptyOutDir: true,
  },
  server: {
    host: "0.0.0.0",
    port: parseInt(process.env.PORT) || 26037,
    allowedHosts: true,
    hmr: false,
  },
  plugins: [
    levelFileWriterPlugin()
  ],
})
